# Generated by Django 5.0 on 2025-10-23 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TagsCat', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Entry title', max_length=200)),
                ('content', models.TextField(help_text='Entry content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this entry is public')),
                ('category', models.ForeignKey(blank=True, help_text='Entry category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='TagsCat.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Entry tags', related_name='entries', to='TagsCat.tag')),
                ('user', models.ForeignKey(help_text='Owner of this journal entry', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='journal_jou_user_id_1ad335_idx'), models.Index(fields=['user', 'category'], name='journal_jou_user_id_b0f9a0_idx')],
            },
        ),
    ]
