# Generated by Django 4.2.25 on 2025-10-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TagsCat', '0001_initial'),
        ('journal', '0001_initial'),
        ('reminder_and_goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='related_goals',
            field=models.ManyToManyField(blank=True, related_name='journals', to='reminder_and_goals.goal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='TagsCat.tag'),
        ),
    ]
