# Generated by Django 5.0 on 2025-10-29 17:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_delete_journalentry'),
    ]
    # This migration became redundant after repository merges; the initial migration
    # already creates the fields and JournalImage model. Keep as a no-op so migration
    # graph remains consistent for historical reasons.
    operations = []
