# Generated by Django 5.2.7 on 2025-10-23 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TagsCat', '0001_initial'),
        ('journal', '0001_initial'),
        ('reminder_and_goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=False, help_text='Whether this entry is public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Entry category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='TagsCat.category')),
                ('related_goals', models.ManyToManyField(blank=True, related_name='journals', to='reminder_and_goals.goal')),
                ('tags', models.ManyToManyField(blank=True, help_text='Entry tags', related_name='entries', to='TagsCat.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
