# Generated by Django 5.0 on 2025-10-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_delete_journalentry'),
        ('journal', '0002_journal_entry_date_journal_hidden_journal_location_and_more'),
    ]

    operations = [
    ]
