# Generated by Django 4.2 on 2025-10-30 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_journal_journalimage_delete_journalentry'),
        ('TagsCat', '0001_initial'),
        ('reminder_and_goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='related_goals',
            field=models.ManyToManyField(blank=True, related_name='journals', to='reminder_and_goals.goal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Entry tags', related_name='entries', to='TagsCat.tag'),
        ),
        migrations.AddField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL),
        ),
    ]
