# Generated by Django 5.0 on 2025-10-30 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TagsCat', '0002_category_tags'),
        ('journal', '0003_journal_related_goals_journal_tags_journal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='TagsCat.category'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='TagsCat.tag'),
        ),
    ]
