# Generated by Django 5.0 on 2025-10-30 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journal_mood'),
        ('journal', '0003_merge_20251029_2131'),
    ]

    operations = [
    ]
