# Generated by Django 5.0 on 2025-10-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_deleted_at'),
        ('journal', '0004_merge_0003_journal_mood_0003_merge_20251029_2131'),
    ]

    operations = [
    ]
