# Generated by Django 5.0 on 2025-10-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_aipromptusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='closing_reflection',
            field=models.TextField(blank=True, help_text='AI-generated or fallback closing reflection', null=True),
        ),
    ]
