# Generated by Django 5.0 on 2025-10-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_journal_closing_reflection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this entry is public'),
        ),
    ]
