# Generated by Django 5.0 on 2025-10-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_initial'),
        ('journal', '0007_journal_closing_reflection'),
    ]

    operations = [
    ]
