# Generated by Django 5.0 on 2025-10-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verified',
            field=models.BooleanField(default=False, help_text='Indicates if the user has verified their email address', verbose_name='verified'),
        ),
    ]
