# Generated by Django 5.0 on 2025-10-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_notifications',
        ),
    ]
