# Generated by Django 5.0 on 2025-10-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_migrate_role_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='joinDate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastLogin',
        ),
    ]
