# Generated by Django 5.0 on 2025-10-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_duplicate_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='journal_pin',
            field=models.CharField(blank=True, help_text='Hashed 4-digit PIN for accessing hidden journals', max_length=128, null=True, verbose_name='journal pin'),
        ),
    ]
