# Generated by Django 4.2 on 2025-10-29 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_duplicate_date_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_username', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Apple ID')),
                ('encrypted_apple_password', models.BinaryField(blank=True, null=True)),
                ('is_apple_connected', models.BooleanField(default=False, verbose_name='Connected to Apple Reminders')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('notification_preferences', models.JSONField(default=dict, help_text='User preferences for notifications', verbose_name='Notification Preferences')),
                ('apple_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_apple_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
