# Generated by Django 4.2 on 2025-10-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_create_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reminders_webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminders_webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
