# Generated by Django 5.0 on 2025-10-30 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag name (e.g., 'Travel', 'Friends')", max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color code (auto-generated if empty)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this tag has been used')),
                ('user', models.ForeignKey(help_text='Owner of this tag', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'University', 'Personal Growth')", max_length=100)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code (e.g., #3B82F6)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier (e.g., 'university', 'heart')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this category', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with this category', related_name='categories', to='TagsCat.tag')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='TagsCat_tag_user_id_8f36af_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', '-usage_count'], name='TagsCat_tag_user_id_2a7c1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'name'], name='TagsCat_cat_user_id_4a5ac8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name')},
        ),
    ]
