# Generated by Django 5.0 on 2025-10-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TagsCat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this category', related_name='categories', to='TagsCat.tag'),
        ),
    ]
