# Generated by Django 5.0 on 2025-10-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TagsCat', '0002_initial'),
        ('TagsCat', '0003_add_color_to_tag'),
    ]

    operations = [
    ]
