# Generated by Django 4.2.25 on 2025-10-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('weekly_auto', 'Rapport Hebdomadaire Automatique'), ('monthly_auto', 'Rapport Mensuel Automatique'), ('mood_analysis', 'Analyse d Humeur IA'), ('writing_insights', 'Insights Écriture IA')], default='weekly_auto', max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('ai_insights', models.JSONField(default=dict)),
                ('trends_analysis', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('psychological_insights', models.JSONField(default=list)),
                ('ai_model_used', models.CharField(default='huggingface', max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur'), ('fallback', 'Fallback Utilisé')], max_length=20)),
                ('ai_model', models.CharField(max_length=100)),
                ('processing_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackofficeDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('mood_analysis', 'Mood Analysis'), ('writing_habits', 'Writing Habits'), ('productivity', 'Productivity Insights'), ('custom', 'Custom Report')], max_length=50)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('filters', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('is_shared', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.FloatField(blank=True, null=True)),
                ('sentiment', models.CharField(choices=[('very_negative', 'Très Négatif'), ('negative', 'Négatif'), ('neutral', 'Neutre'), ('positive', 'Positif'), ('very_positive', 'Très Positif')], default='neutral', max_length=20)),
                ('word_count', models.IntegerField(default=0)),
                ('emotions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reading_time', models.IntegerField(default=0)),
                ('keywords', models.JSONField(default=list)),
                ('themes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MoodTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average_mood', models.FloatField()),
                ('entry_count', models.IntegerField(default=0)),
                ('dominant_emotion', models.CharField(blank=True, max_length=50)),
                ('mood_volatility', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_entries', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('average_mood', models.FloatField(default=0)),
                ('average_word_count', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_words_written', models.IntegerField(default=0)),
                ('favorite_topics', models.JSONField(default=list)),
                ('writing_consistency', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('insights', models.JSONField(default=dict)),
                ('patterns', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achievements', models.JSONField(default=list)),
                ('challenges', models.JSONField(default=list)),
            ],
        ),
    ]
