# Generated by Django 4.2.25 on 2025-10-29 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statistics_and_insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryanalytics',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='entryanalytics',
            name='reading_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entryanalytics',
            name='themes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='moodtrend',
            name='dominant_emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='moodtrend',
            name='mood_volatility',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='favorite_topics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='total_words_written',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='writing_consistency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyinsight',
            name='achievements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='weeklyinsight',
            name='challenges',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('mood_analysis', 'Mood Analysis'), ('writing_habits', 'Writing Habits'), ('productivity', 'Productivity Insights'), ('custom', 'Custom Report')], max_length=50)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('filters', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('is_shared', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
