# Generated by Django 4.2.25 on 2025-10-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_and_insights', '0002_entryanalytics_keywords_entryanalytics_reading_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customreport',
            name='is_active',
        ),
    ]
