# Generated by Django 4.2.25 on 2025-10-29 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statistics_and_insights', '0003_remove_customreport_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackofficeDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur'), ('fallback', 'Fallback Utilisé')], max_length=20)),
                ('ai_model', models.CharField(max_length=100)),
                ('processing_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIGeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('weekly_auto', 'Rapport Hebdomadaire Automatique'), ('monthly_auto', 'Rapport Mensuel Automatique'), ('mood_analysis', 'Analyse d Humeur IA'), ('writing_insights', 'Insights Écriture IA')], default='weekly_auto', max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('ai_insights', models.JSONField(default=dict)),
                ('trends_analysis', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('psychological_insights', models.JSONField(default=list)),
                ('ai_model_used', models.CharField(default='huggingface', max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
