# Generated by Django 5.0 on 2025-10-31 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_add_related_goals_table'),
        ('reminder_and_goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalsuggestion',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_goal_suggestions', to='journal.journal'),
        ),
    ]
