# Generated by Django 4.2.25 on 2025-10-30 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminder_and_goals', '0001_initial'),
        ('journal', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_and_goals_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalsuggestion',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_goal_suggestions', to='journal.journal'),
        ),
        migrations.AddField(
            model_name='goalsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_and_goals_goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
