# Generated by Django 4.2 on 2025-10-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_and_goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['reminder_time']},
        ),
        migrations.AddField(
            model_name='reminder',
            name='apple_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='apple_reminder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_synced_with_apple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
