# Generated by Django 4.2 on 2025-10-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_and_goals', '0002_goal_completed_at_goal_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterField(
            model_name='goal',
            name='target',
            field=models.PositiveIntegerField(help_text='Target number of journal entries'),
        ),
    ]
