# Generated by Django 4.2 on 2025-10-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_and_goals', '0002_alter_reminder_options_reminder_apple_calendar_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
