# Generated by Django 5.0 on 2025-10-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_and_goals', '0003_alter_goal_options_alter_goal_target'),
    ]

    operations = [
        # Add missing columns to Goal table
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'reminder_and_goals_goal' 
                 AND column_name = 'is_completed' 
                 AND table_schema = DATABASE()) = 0,
                'ALTER TABLE reminder_and_goals_goal ADD COLUMN is_completed BOOLEAN DEFAULT FALSE',
                'SELECT "Column is_completed already exists"'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE reminder_and_goals_goal DROP COLUMN is_completed;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'reminder_and_goals_goal' 
                 AND column_name = 'completed_at' 
                 AND table_schema = DATABASE()) = 0,
                'ALTER TABLE reminder_and_goals_goal ADD COLUMN completed_at DATETIME NULL',
                'SELECT "Column completed_at already exists"'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE reminder_and_goals_goal DROP COLUMN completed_at;"
        ),
        # Add missing columns to Reminder table
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'reminder_and_goals_reminder' 
                 AND column_name = 'apple_reminder_id' 
                 AND table_schema = DATABASE()) = 0,
                'ALTER TABLE reminder_and_goals_reminder ADD COLUMN apple_reminder_id VARCHAR(255) NULL',
                'SELECT "Column apple_reminder_id already exists"'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE reminder_and_goals_reminder DROP COLUMN apple_reminder_id;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'reminder_and_goals_reminder' 
                 AND column_name = 'apple_calendar_id' 
                 AND table_schema = DATABASE()) = 0,
                'ALTER TABLE reminder_and_goals_reminder ADD COLUMN apple_calendar_id VARCHAR(255) NULL',
                'SELECT "Column apple_calendar_id already exists"'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE reminder_and_goals_reminder DROP COLUMN apple_calendar_id;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'reminder_and_goals_reminder' 
                 AND column_name = 'is_synced_with_apple' 
                 AND table_schema = DATABASE()) = 0,
                'ALTER TABLE reminder_and_goals_reminder ADD COLUMN is_synced_with_apple BOOLEAN DEFAULT FALSE',
                'SELECT "Column is_synced_with_apple already exists"'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE reminder_and_goals_reminder DROP COLUMN is_synced_with_apple;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'reminder_and_goals_reminder' 
                 AND column_name = 'last_sync_at' 
                 AND table_schema = DATABASE()) = 0,
                'ALTER TABLE reminder_and_goals_reminder ADD COLUMN last_sync_at DATETIME NULL',
                'SELECT "Column last_sync_at already exists"'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE reminder_and_goals_reminder DROP COLUMN last_sync_at;"
        ),
    ]
