# Generated by Django 5.0 on 2025-10-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_and_goals', '0004_auto_20251030_2157'),
    ]

    operations = [
        # Add missing columns to Reminder table only
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'reminder_and_goals_reminder' 
                 AND column_name = 'apple_reminder_id' 
                 AND table_schema = DATABASE()) = 0,
                'ALTER TABLE reminder_and_goals_reminder ADD COLUMN apple_reminder_id VARCHAR(255) NULL',
                'SELECT "Column apple_reminder_id already exists"'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="SELECT 'No reverse needed';"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'reminder_and_goals_reminder' 
                 AND column_name = 'apple_calendar_id' 
                 AND table_schema = DATABASE()) = 0,
                'ALTER TABLE reminder_and_goals_reminder ADD COLUMN apple_calendar_id VARCHAR(255) NULL',
                'SELECT "Column apple_calendar_id already exists"'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="SELECT 'No reverse needed';"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'reminder_and_goals_reminder' 
                 AND column_name = 'is_synced_with_apple' 
                 AND table_schema = DATABASE()) = 0,
                'ALTER TABLE reminder_and_goals_reminder ADD COLUMN is_synced_with_apple BOOLEAN DEFAULT FALSE',
                'SELECT "Column is_synced_with_apple already exists"'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="SELECT 'No reverse needed';"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'reminder_and_goals_reminder' 
                 AND column_name = 'last_sync_at' 
                 AND table_schema = DATABASE()) = 0,
                'ALTER TABLE reminder_and_goals_reminder ADD COLUMN last_sync_at DATETIME NULL',
                'SELECT "Column last_sync_at already exists"'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="SELECT 'No reverse needed';"
        ),
    ]